export default [
  {
    name: "Java",
    price: 22.9,
    authorId: 1,
    description: "Java course",
    categoryId: 1,
    image:
      "https://www.google.com/url?sa=i&url=http%3A%2F%2Fqnimate.com%2Funderstanding-html-img-tag%2F&psig=AOvVaw09YN7yvTYGfU7mmbFup6jZ&ust=1614329218355000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKjk9I7ThO8CFQAAAAAdAAAAABAI",
  },
  {
    name: "Python",
    price: 10.9,
    authorId: 1,
    description: "Is python course",
    categoryId: 2,
  },
  {
    name: "Rust",
    price: 30.9,
    authorId: 2,
    description: "Is rust course",
    categoryId: 2,
  },
  {
    name: "Rust",
    price: 30.9,
    authorId: 2,
    description: "Is rust course",
    categoryId: 2,
  },
  {
    name: "Rust",
    price: 30.9,
    authorId: 2,
    description: "Is rust course",
    categoryId: 2,
  },
  {
    name: "Rust",
    price: 30.9,
    authorId: 2,
    description: "Is rust course",
    categoryId: 2,
  },
  {
    name: "Rust",
    price: 30.9,
    authorId: 2,
    description: "Is rust course",
    categoryId: 2,
  },
  {
    name: "Rust",
    price: 30.9,
    authorId: 2,
    description: "Is rust course",
    categoryId: 2,
  },
];
