export default [
  {
    id: 1,
    name: "Introduction To The Course",
    video:
      "https://youtu.be/ntLJmHOJ0ME?list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q",
    document: "",
    lectureId: 1,
  },
  {
    id: 2,
    name: "Remaster in Progress",
    video: "https://www.youtube.com/watch?v=hKB-YGF14SY",
    document: "",
    lectureId: 1,
  },
  {
    id: 3,
    name: "Java Tutorial: Variables and Data Types in Java Programming",
    video: "https://www.youtube.com/watch?v=O45nZc3rP20",
    document: "",
    lectureId: 1,
  },
  {
    id: 4,
    name: "How to Install Java JDK on Windows 10 ( with JAVA_HOME )",
    video: "https://www.youtube.com/watch?v=IJ-PJbvJBGs",
    document: "",
    lectureId: 2,
  },
  {
    id: 5,
    name:
      "How to Set Up Java Development in Visual Studio Code on Windows | vsCode Java Development Basics",
    video: "https://www.youtube.com/watch?v=ClU9N4ub_Ko",
    document: "",
    lectureId: 2,
  },
  {
    id: 6,
    name: "Creating your first Java application with IntelliJ IDEA",
    video: "https://www.youtube.com/watch?v=H_XxH66lm3U",
    document: "",
    lectureId: 3,
  },
  {
    id: 7,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 4,
  },
  {
    id: 8,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 5,
  },
  {
    id: 9,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 6,
  },
  {
    id: 10,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 7,
  },
  {
    id: 11,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 8,
  },
  {
    id: 12,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 9,
  },
  {
    id: 13,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 10,
  },
  {
    id: 14,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 11,
  },
  {
    id: 15,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 12,
  },
  {
    id: 16,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 13,
  },
  {
    id: 17,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 14,
  },
  {
    id: 18,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 15,
  },
  {
    id: 19,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 16,
  },
  {
    id: 20,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 17,
  },
  {
    id: 21,
    name: "HOW TO PROGRAM - Getting Started!",
    video: "https://www.youtube.com/watch?v=N775KsWQVkw",
    document: "",
    lectureId: 18,
  },
];
